name: BHARATH

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}  

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - run: npm ci
      - run: npm run build

      - name: Use Secret
        run: echo " Key is $JWT_SECRET"   

  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}   

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - run: npm ci
      - run: npm test